package defaultpackage;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.nio.file.Path;
import java.util.ArrayList;
import defaultpackage.MainFrame;
import java.awt.event.KeyEvent;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tilak
 */
public class FileChooser_for_source extends javax.swing.JFrame {
    ArrayList<File> source=new ArrayList<File>();
   MainFrame mframe;
    /**
     * Creates new form FileChooser
     */
    public FileChooser_for_source(MainFrame frame) {
        mframe=frame;
          Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
       int w=dim.width;
       int h=dim.height;
      
       Dimension d=new Dimension();
       d.setSize(w/2, h/1.5);
       this.setPreferredSize(d);
       this.setLocation((w-w/2)/2, (h-h/2)/2);
       this.setTitle("File Copier");
        initComponents();
      
    }
    void dirstructure(File s)
    {
        source.add(s);
        System.out.println(s.toPath().toString());
        File[] temp=s.listFiles();
        for(File k:temp)
        {
            if(k.isDirectory())
                dirstructure(k);
             System.out.println(k.toPath().toAbsolutePath().toString());
            source.add(k);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jFileChooser1 = new javax.swing.JFileChooser();

        setTitle("Press Enter to Select Files");
        setAlwaysOnTop(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout());

        jScrollPane1.setAutoscrolls(true);

        jFileChooser1.setCurrentDirectory(Paths.get(System.getProperty("user.home")).toFile()

        );
        jFileChooser1.setFileHidingEnabled(false);
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser1.setToolTipText("");
        jFileChooser1.setMultiSelectionEnabled(true);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jFileChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFileChooser1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFileChooser1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jFileChooser1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
void jFileChooser1ActionPerformed(java.awt.event.KeyEvent evt){
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
            System.out.print("fdg");
    };
    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed

        JOptionPane.showMessageDialog(this,"Added Successfully");
        File[] a=jFileChooser1.getSelectedFiles();
      long size=0;
      if(a.length!=0)
      {
      
      File cur=jFileChooser1.getCurrentDirectory();
       String pwd=cur.toPath().toString();
    //  JOptionPane.showMessageDialog(rootPane, mframe);
      
      System.out.println("PWD IS "+pwd);
      for(File k:a)
      {
          
          if(k.isDirectory())
          {
              
           dirstructure(k);
          
          
          }
          else
          {
              System.out.println(k.toPath().toString().replace(cur.toPath().toString(),""));
              source.add(k);
          }
           
      }
       
               
      
      
   mframe.files_copy(source,pwd);
     jFileChooser1.setCurrentDirectory(jFileChooser1.getCurrentDirectory());
  jFileChooser1.setVisible(true);

  // System.exit(0);
 //  Thread.dumpStack();
      }
// TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
mframe.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jFileChooser1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFileChooser1KeyPressed



        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1KeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jFileChooser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFileChooser1KeyTyped
      
    }//GEN-LAST:event_jFileChooser1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooser_for_source(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
