package defaultpackage;


import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import defaultpackage.MainFrame;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tilak
 */
public class FileChooser_for_dest extends javax.swing.JFrame {
    ArrayList<File> dest=new ArrayList<File>();
   MainFrame mframe;
    /**
     * Creates new form FileChooser
     */
    public FileChooser_for_dest(MainFrame frame) {
        mframe=frame;
          Dimension dim=Toolkit.getDefaultToolkit().getScreenSize();
       int w=dim.width;
       int h=dim.height;
      
       Dimension d=new Dimension();
       d.setSize(w/2, h/1.5);
       this.setPreferredSize(d);
       this.setLocation((w-w/2)/2, (h-h/2)/2);
       this.setTitle("File Copier");
        initComponents();
           
        
    }
    /*void dirstructure(File d)
    {
        File[] temp=d.listFiles();
        for(File k:temp)
        {
            if(k.isDirectory())
                dirstructure(k);
             System.out.println(k.toPath().toString());
            dest.add(k);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jFileChooser1 = new javax.swing.JFileChooser();

        setTitle("Press Enter to Select Files");
        setAlwaysOnTop(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setAutoscrolls(true);

        jFileChooser1.setCurrentDirectory(Paths.get(System.getProperty("user.home")).toFile()

        );
        jFileChooser1.setFileHidingEnabled(false);
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.setMultiSelectionEnabled(true);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        jScrollPane1.setViewportView(jFileChooser1);

        getContentPane().add(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
       JOptionPane.showMessageDialog(this,"Added Successfully");
       
        File a=jFileChooser1.getSelectedFile();
        if(a!=null)
        {
            
        
      int l=dest.size();
      for(int z=0;z<l;z++)
      dest.remove(l);
          if(a.isDirectory())
          {
             
              dest.add(a);
         
          
          
          }
          
        
    
       
               
       
       
   mframe.files_dest(dest);
      jFileChooser1.setCurrentDirectory(jFileChooser1.getCurrentDirectory());
      jFileChooser1.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
mframe.setEnabled(true);         // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileChooser_for_source.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileChooser_for_source(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
