
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this tem

@Override
public void paintIcon(Component c, Graphics g, int x, int y) {
throw new UnsupportedOperationException("Not supported yet.");
}

@Override
public int getIconWidth() {
throw new UnsupportedOperationException("Not supported yet.");
}

@Override
public int getIconHeight() {
throw new UnsupportedOperationException("Not supported yet.");
}
}late, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Home.java
 *
 * Created on Aug 18, 2012, 5:27:53 PM
 */
/**
 *
 * @author Tilak PC
 */
public class Home extends javax.swing.JFrame {

    
  
    String mysqlpass;
    int start = 0;

    /** Creates new form Home */
    public Home() {
        initComponents();














    }

    public Home(String mysqlpassword) {
        initComponents();
        mysqlpass=mysqlpassword;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;
        this.setLocation(x, y);



        Calendar cal = Calendar.getInstance();
        jldate.setText(cal.getTime().toString());

        cpassword_button.setVisible(false);
        removepass_button.setVisible(false);
        newadd_button.setVisible(false);
        removead_button.setVisible(false);
        studnetsrch_button.setVisible(false);
        recfees_button.setVisible(false);
        regteach_button.setVisible(false);
        feedef_button.setVisible(false);
        entermarks_button.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel5.setVisible(false);
        shut_button.setVisible(false);
        jLabel8.setVisible(false);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        shut_button = new javax.swing.JButton();
        cpassword_button = new javax.swing.JButton();
        newadd_button = new javax.swing.JButton();
        studnetsrch_button = new javax.swing.JButton();
        feedef_button = new javax.swing.JButton();
        recfees_button = new javax.swing.JButton();
        entermarks_button = new javax.swing.JButton();
        removead_button = new javax.swing.JButton();
        regteach_button = new javax.swing.JButton();
        removepass_button = new javax.swing.JButton();
        start_button = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        iexplore_button = new javax.swing.JButton();
        notepad_button = new javax.swing.JButton();
        control_button = new javax.swing.JButton();
        aero_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cal_button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jldate = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut.png"))); // NOI18N
        jLabel8.setAutoscrolls(true);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -30, 1310, 600));

        shut_button.setFont(new java.awt.Font("Calibri", 0, 8)); // NOI18N
        shut_button.setForeground(new java.awt.Color(255, 255, 255));
        shut_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shutdown.png"))); // NOI18N
        shut_button.setText("Shutdown");
        shut_button.setContentAreaFilled(false);
        shut_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        shut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shut_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(shut_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 130, 40));

        cpassword_button.setBackground(new java.awt.Color(255, 255, 255));
        cpassword_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        cpassword_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog-password.png"))); // NOI18N
        cpassword_button.setText("Change Password");
        cpassword_button.setBorder(null);
        cpassword_button.setBorderPainted(false);
        cpassword_button.setContentAreaFilled(false);
        cpassword_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cpassword_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cpassword_buttonMouseEntered(evt);
            }
        });
        cpassword_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassword_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cpassword_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 50));

        newadd_button.setBackground(new java.awt.Color(255, 255, 255));
        newadd_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        newadd_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/list-add.png"))); // NOI18N
        newadd_button.setText("   New Admission");
        newadd_button.setBorder(null);
        newadd_button.setContentAreaFilled(false);
        newadd_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        newadd_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newadd_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(newadd_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 40));

        studnetsrch_button.setBackground(new java.awt.Color(255, 255, 255));
        studnetsrch_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        studnetsrch_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        studnetsrch_button.setText("   Student Search");
        studnetsrch_button.setBorder(null);
        studnetsrch_button.setContentAreaFilled(false);
        studnetsrch_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        studnetsrch_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studnetsrch_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(studnetsrch_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 60));

        feedef_button.setBackground(new java.awt.Color(255, 255, 255));
        feedef_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        feedef_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        feedef_button.setText(" Fee Defaulters");
        feedef_button.setBorder(null);
        feedef_button.setContentAreaFilled(false);
        feedef_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        feedef_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedef_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(feedef_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, 40));

        recfees_button.setBackground(new java.awt.Color(255, 255, 255));
        recfees_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        recfees_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/money.png"))); // NOI18N
        recfees_button.setText(" Recieve Fees");
        recfees_button.setBorder(null);
        recfees_button.setContentAreaFilled(false);
        recfees_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        recfees_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recfees_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(recfees_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 220, 30));

        entermarks_button.setBackground(new java.awt.Color(255, 255, 255));
        entermarks_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        entermarks_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture2.png"))); // NOI18N
        entermarks_button.setText("Enter Marks");
        entermarks_button.setBorder(null);
        entermarks_button.setContentAreaFilled(false);
        entermarks_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        entermarks_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entermarks_buttonMouseEntered(evt);
            }
        });
        entermarks_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entermarks_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(entermarks_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 220, 20));

        removead_button.setBackground(new java.awt.Color(255, 255, 255));
        removead_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removead_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3f.png"))); // NOI18N
        removead_button.setText(" Remove Admission");
        removead_button.setBorder(null);
        removead_button.setContentAreaFilled(false);
        removead_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removead_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removead_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(removead_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 230, 40));

        regteach_button.setBackground(new java.awt.Color(255, 255, 255));
        regteach_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        regteach_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture1.png"))); // NOI18N
        regteach_button.setText("Register Teacher");
        regteach_button.setBorder(null);
        regteach_button.setContentAreaFilled(false);
        regteach_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        regteach_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regteach_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(regteach_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 220, 40));

        removepass_button.setBackground(new java.awt.Color(255, 255, 255));
        removepass_button.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        removepass_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog-password.png"))); // NOI18N
        removepass_button.setText("Remove Password");
        removepass_button.setBorder(null);
        removepass_button.setContentAreaFilled(false);
        removepass_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        removepass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removepass_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(removepass_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 220, 40));

        start_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/start-here.png"))); // NOI18N
        start_button.setContentAreaFilled(false);
        start_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                start_buttonMouseClicked(evt);
            }
        });
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(start_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 80, 50));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<HTML>Version 1.1<P>\nDesigned By<p>\nTilak<p>\nTushar");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 90, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dialog-information.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 80, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormatFactorymenu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 360, 580));

        iexplore_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iexplorer.png"))); // NOI18N
        iexplore_button.setContentAreaFilled(false);
        iexplore_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iexplore_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(iexplore_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 66, 57));

        notepad_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notepad.png"))); // NOI18N
        notepad_button.setContentAreaFilled(false);
        notepad_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepad_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(notepad_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 67, 57));

        control_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/control.png"))); // NOI18N
        control_button.setContentAreaFilled(false);
        control_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                control_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(control_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 69, 57));

        aero_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut.png"))); // NOI18N
        aero_button.setBorderPainted(false);
        aero_button.setContentAreaFilled(false);
        aero_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aero_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aero_buttonMouseExited(evt);
            }
        });
        aero_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aero_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(aero_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, 40, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 510, 40, 60));

        cal_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calc.png"))); // NOI18N
        cal_button.setContentAreaFilled(false);
        cal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cal_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cal_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 68, 57));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1240, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shut.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 1200, 60));

        jldate.setEditable(false);
        jldate.setColumns(20);
        jldate.setFont(new java.awt.Font("Monospaced", 1, 22)); // NOI18N
        jldate.setLineWrap(true);
        jldate.setRows(5);
        jldate.setOpaque(false);
        getContentPane().add(jldate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 50, 110, 100));

        jLabel4.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cal.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void starthide() {
        cpassword_button.setVisible(false);
        removepass_button.setVisible(false);
        newadd_button.setVisible(false);
        removead_button.setVisible(false);
        studnetsrch_button.setVisible(false);
        recfees_button.setVisible(false);
        regteach_button.setVisible(false);
        feedef_button.setVisible(false);
        entermarks_button.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel5.setVisible(false);
        shut_button.setVisible(false);
    }

    public void startshow() {
        cpassword_button.setVisible(true);
        removepass_button.setVisible(true);
        newadd_button.setVisible(true);
        removead_button.setVisible(true);
        studnetsrch_button.setVisible(true);
        recfees_button.setVisible(true);
        regteach_button.setVisible(true);
        feedef_button.setVisible(true);
        entermarks_button.setVisible(true);
        jLabel1.setVisible(true);
        jLabel3.setVisible(true);
        jLabel5.setVisible(true);
        shut_button.setVisible(true);
    }

private void iexplore_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iexplore_buttonActionPerformed
    start = 0;
    starthide();
    try {
        Runtime.getRuntime().exec("C:/Program Files/Internet Explorer/iexplore.exe");// TODO add your handling code here:
    } catch (IOException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }// TODO add your handling code here:
}//GEN-LAST:event_iexplore_buttonActionPerformed

private void notepad_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepad_buttonActionPerformed
    start = 0;
    starthide();
    try {
        Runtime.getRuntime().exec("C:/Windows/notepad.exe");// TODO add your handling code here:
    } catch (IOException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }// TODO add your handling code here:
}//GEN-LAST:event_notepad_buttonActionPerformed

private void control_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_control_buttonActionPerformed
    start = 0;
    starthide();
    try {
        Runtime.getRuntime().exec("C:/WINDOWS/system32/control.exe");// TODO add your handling code here:
    } catch (IOException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }// TODO add your handling code here:
}//GEN-LAST:event_control_buttonActionPerformed

private void cal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cal_buttonActionPerformed
    start = 0;
    try {
        Runtime.getRuntime().exec("C:/Windows/System32/calc.exe");// TODO add your handling code here:
    } catch (IOException ex) {
        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
    }
    starthide();
}//GEN-LAST:event_cal_buttonActionPerformed

private void entermarks_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entermarks_buttonActionPerformed
    cpassword_button.setVisible(false);
    starthide();
    new marks_rec(mysqlpass).setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_entermarks_buttonActionPerformed

private void regteach_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regteach_buttonActionPerformed
    starthide();
    new teacher_rec(mysqlpass).setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_regteach_buttonActionPerformed

private void feedef_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedef_buttonActionPerformed
    starthide();
    new Fee_Defaulters(mysqlpass).setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_feedef_buttonActionPerformed

private void recfees_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recfees_buttonActionPerformed
    starthide();
    new RecieveFees(mysqlpass).setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_recfees_buttonActionPerformed

private void studnetsrch_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studnetsrch_buttonActionPerformed
    starthide();
    new Student_search(mysqlpass).setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_studnetsrch_buttonActionPerformed

private void removead_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removead_buttonActionPerformed
    starthide();
    new Remove_admission(mysqlpass).setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_removead_buttonActionPerformed

private void newadd_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newadd_buttonActionPerformed
    starthide();
    new Image_location(mysqlpass).setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_newadd_buttonActionPerformed

private void removepass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removepass_buttonActionPerformed
    starthide();
    new RemovePass(mysqlpass).setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_removepass_buttonActionPerformed

private void cpassword_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassword_buttonActionPerformed
    starthide();
    new ChangePass(mysqlpass).setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_cpassword_buttonActionPerformed

private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    starthide();// TODO add your handling code here:
}//GEN-LAST:event_formMouseClicked

private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed

    start = start + 1;
    if (start == 1) {
        startshow();
    } else {
        starthide();
        start = 0;
    }

    // TODO add your handling code here:
}//GEN-LAST:event_start_buttonActionPerformed

private void start_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_start_buttonMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_start_buttonMouseClicked

private void shut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shut_buttonActionPerformed
    jLabel8.setVisible(true);
    int a = JOptionPane.showConfirmDialog(this, "Confirm Exit");
    if (a == 0) {
        System.exit(0);// TODO add your handling code here:
    }
    if (a == 1) {
        jLabel8.setVisible(false);
    }
    if (a == 2) {
        jLabel8.setVisible(false);
    }

}//GEN-LAST:event_shut_buttonActionPerformed

private void entermarks_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entermarks_buttonMouseEntered
    entermarks_button.setSelected(true);// TODO add your handling code here:
}//GEN-LAST:event_entermarks_buttonMouseEntered

private void cpassword_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpassword_buttonMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_cpassword_buttonMouseEntered

private void aero_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aero_buttonActionPerformed
    this.toFront();// TODO add your handling code here:
}//GEN-LAST:event_aero_buttonActionPerformed

private void aero_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aero_buttonMouseEntered
    this.toFront();// TODO add your handling code here:
}//GEN-LAST:event_aero_buttonMouseEntered

private void aero_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aero_buttonMouseExited
    this.toBack();// TODO add your handling code here:
}//GEN-LAST:event_aero_buttonMouseExited

private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
    start = 0;
    cpassword_button.setVisible(false);
    starthide();// TODO add your handling code here:
}//GEN-LAST:event_jLabel7MouseClicked



    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                new Home().setVisible(true);
                

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aero_button;
    private javax.swing.JButton cal_button;
    private javax.swing.JButton control_button;
    private javax.swing.JButton cpassword_button;
    private javax.swing.JButton entermarks_button;
    private javax.swing.JButton feedef_button;
    private javax.swing.JButton iexplore_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jldate;
    private javax.swing.JButton newadd_button;
    private javax.swing.JButton notepad_button;
    private javax.swing.JButton recfees_button;
    private javax.swing.JButton regteach_button;
    private javax.swing.JButton removead_button;
    private javax.swing.JButton removepass_button;
    private javax.swing.JButton shut_button;
    private javax.swing.JToggleButton start_button;
    private javax.swing.JButton studnetsrch_button;
    // End of variables declaration//GEN-END:variables
}
