
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * photopath.java
 *
 * Created on Nov 26, 2012, 10:51:38 AM
 */
/**
 *
 * @author Tilak
 */
public class Image_location extends javax.swing.JFrame {
String mysqlpass;

    /** Creates new form photopath */
    public Image_location() {
        initComponents();
    }
    public Image_location(String mysqlpassword)
    {
        mysqlpass=mysqlpassword;
        initComponents();
        
         
         JOptionPane.showMessageDialog(this,"Select Passport size photograph for new admission");
        int a=JOptionPane.showConfirmDialog(this,"Do you have a photograph");
        
        if(a==0)
        {
            
        }
        else if(a==2)
        {
            try {
                this.wait();
            } catch (InterruptedException ex) {
                Logger.getLogger(Image_location.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else  if(a==1)      
        {
                    new NewAddmission(mysqlpass,"").setVisible(true);
                    try {
                this.wait();
            } catch (InterruptedException ex) {
                Logger.getLogger(Image_location.class.getName()).log(Level.SEVERE, null, ex);
            }
                    
                    
        }
        else
        {
            try {
                this.wait();
            } catch (InterruptedException ex) {
                Logger.getLogger(Image_location.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filechooser = new javax.swing.JFileChooser();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filechooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        filechooser.setControlButtonsAreShown(false);
        filechooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechooserActionPerformed(evt);
            }
        });
        getContentPane().add(filechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String filename;

private void filechooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechooserActionPerformed
        
        filename = filechooser.getSelectedFile().getPath().replace("\\","//");
        System.out.print(filename);
        new NewAddmission(mysqlpass,filename).show();
        
        
        this.setVisible(false);
        
        
}//GEN-LAST:event_filechooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Image_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Image_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Image_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Image_location.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Image_location().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser filechooser;
    // End of variables declaration//GEN-END:variables
}
