

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LOGIN.java
 *
 * Created on Aug 20, 2012, 9:28:52 PM
 */
/**
 *
 * @author Tilak PC
 */
public class LOGIN extends javax.swing.JFrame {
    
    String currentmysqlpassword;

    /** Creates new form LOGIN */
    public LOGIN() {
        initComponents();
        mysql_label.setVisible(false);
        mysqlpass_text.setVisible(false);
        login_button.setVisible(false);
        cancel_button.setVisible(false);
        this.setVisible(true);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mysql_label = new javax.swing.JLabel();
        mysqlpass_text = new javax.swing.JPasswordField();
        login_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        splash = new javax.swing.JLabel();
        databasepass_button = new javax.swing.JButton();
        started_button = new javax.swing.JButton();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mysql_label.setText("Enter mysql database password ");
        mysql_label.setName("mysql_label"); // NOI18N
        getContentPane().add(mysql_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        mysqlpass_text.setName("mysqlpass_text"); // NOI18N
        getContentPane().add(mysqlpass_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 170, -1));

        login_button.setText("LOGIN");
        login_button.setName("login_button"); // NOI18N
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        cancel_button.setText("Cancel");
        cancel_button.setName("cancel_button"); // NOI18N
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        splash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        splash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/splash.gif"))); // NOI18N
        splash.setName("splash"); // NOI18N
        getContentPane().add(splash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 120));

        databasepass_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data.png"))); // NOI18N
        databasepass_button.setName("databasepass_button"); // NOI18N
        databasepass_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databasepass_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(databasepass_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 310, 60));

        started_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/started.png"))); // NOI18N
        started_button.setName("started_button"); // NOI18N
        started_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                started_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(started_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 310, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void started_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_started_buttonActionPerformed


    mysql_label.setVisible(true);
        login_button.setVisible(true);
        cancel_button.setVisible(true);
        mysqlpass_text.setVisible(true);
        
        started_button.setVisible(false);
        splash.setVisible(false);
        databasepass_button.setVisible(false);// TODO add your handling code here:
}//GEN-LAST:event_started_buttonActionPerformed

private void databasepass_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databasepass_buttonActionPerformed
new login_databasepass().setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_databasepass_buttonActionPerformed

private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
currentmysqlpassword=mysqlpass_text.getText();

String query="SET PASSWORD=PASSWORD('"+(currentmysqlpassword)+"')";
try{
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/","root",currentmysqlpassword);
            java.sql.Statement stmt=con.createStatement();
            stmt.execute(query);

    this.setVisible(false);
        new Software_pass(currentmysqlpassword).setVisible(true);
    
    
}
catch(Exception e){
    
    JOptionPane.showMessageDialog(this,"Wrong Password");
    mysqlpass_text.setText("");
    
}// TODO add your handling code here:
}//GEN-LAST:event_login_buttonActionPerformed

private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
mysql_label.setVisible(false);
        login_button.setVisible(false);
        cancel_button.setVisible(false);
        mysqlpass_text.setVisible(false);
        
        started_button.setVisible(true);
        splash.setVisible(true);
        databasepass_button.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton databasepass_button;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel mysql_label;
    private javax.swing.JPasswordField mysqlpass_text;
    private javax.swing.JLabel splash;
    private javax.swing.JButton started_button;
    // End of variables declaration//GEN-END:variables
}
