
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecieveFees.java
 *
 * Created on Aug 21, 2012, 10:33:50 PM
 */
/**
 *
 * @author Tilak PC
 */
public class RecieveFees extends javax.swing.JFrame {
String Classs;
String number;
String enroll;
String feesdate;
String conveyence,mysqlpass;
    /** Creates new form RecieveFees */
    public RecieveFees() {
        initComponents();
       

    }
    public RecieveFees( String mysqlpassword)
    {
        initComponents();
       mysqlpass=mysqlpassword;
        Date now = new Date(); 
SimpleDateFormat formatter = new SimpleDateFormat( "yyyy/MM/dd" ); 
date_button.setText( formatter.format( now ) ); 
generate_button.setEnabled(false);
submit_button.setEnabled(false);
Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        name_text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        class_text = new javax.swing.JTextField();
        section_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        img_label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        date_button = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        editdate_check = new javax.swing.JCheckBox();
        tution_text = new javax.swing.JTextField();
        conveyence_text = new javax.swing.JTextField();
        latefees_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        submit_button = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        xtrafees_text = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        scholar_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        verify_Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cash_radio = new javax.swing.JRadioButton();
        cheque_radio = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        generate_button = new javax.swing.JButton();
        payment_combo = new javax.swing.JComboBox();
        xtrafees_check = new javax.swing.JCheckBox();
        latefees_check = new javax.swing.JCheckBox();
        clear_buttton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowDeiconified(java.awt.event.WindowEvent evt) {
                formWindowDeiconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fee Book"));
        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);

        name_text.setEditable(false);
        name_text.setName("name_text"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel2.setText(" Name");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel3.setText("Class");
        jLabel3.setName("jLabel3"); // NOI18N

        class_text.setEditable(false);
        class_text.setName("class_text"); // NOI18N

        section_text.setEditable(false);
        section_text.setName("section_text"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Sec");
        jLabel6.setName("jLabel6"); // NOI18N

        img_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nophoto.png"))); // NOI18N
        img_label.setName("img_label"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(class_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(section_text, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(img_label, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_label, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(class_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(section_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setOpaque(false);

        date_button.setEditable(false);
        date_button.setName("date_button"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("Date");
        jLabel4.setName("jLabel4"); // NOI18N

        editdate_check.setText("Click to Edit");
        editdate_check.setContentAreaFilled(false);
        editdate_check.setName("editdate_check"); // NOI18N
        editdate_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editdate_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_button, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editdate_check, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editdate_check))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tution_text.setEditable(false);
        tution_text.setName("tution_text"); // NOI18N

        conveyence_text.setEditable(false);
        conveyence_text.setName("conveyence_text"); // NOI18N

        latefees_text.setEditable(false);
        latefees_text.setName("latefees_text"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Late Fees");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Conveyence Fees");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Tution Fees");
        jLabel8.setName("jLabel8"); // NOI18N

        submit_button.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        submit_button.setText("SUBMIT");
        submit_button.setName("submit_button"); // NOI18N
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel12.setText("Extra Fees");
        jLabel12.setName("jLabel12"); // NOI18N

        xtrafees_text.setEditable(false);
        xtrafees_text.setName("xtrafees_text"); // NOI18N

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setOpaque(false);

        scholar_textfield.setName("scholar_textfield"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Scholar No.");
        jLabel5.setName("jLabel5"); // NOI18N

        verify_Button.setText("VERIFY");
        verify_Button.setName("verify_Button"); // NOI18N
        verify_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scholar_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(verify_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scholar_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verify_Button))
                .addGap(27, 27, 27))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setOpaque(false);

        buttonGroup1.add(cash_radio);
        cash_radio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cash_radio.setText("Cash");
        cash_radio.setName("cash_radio"); // NOI18N
        cash_radio.setOpaque(false);
        cash_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cash_radioActionPerformed(evt);
            }
        });

        buttonGroup1.add(cheque_radio);
        cheque_radio.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cheque_radio.setText("Cheque");
        cheque_radio.setName("cheque_radio"); // NOI18N
        cheque_radio.setOpaque(false);
        cheque_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheque_radioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Payment Mode");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setText("Payment upto");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel14.setText("months");
        jLabel14.setName("jLabel14"); // NOI18N

        generate_button.setText("Generate");
        generate_button.setName("generate_button"); // NOI18N
        generate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_buttonActionPerformed(evt);
            }
        });

        payment_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "3", "6", "12" }));
        payment_combo.setName("payment_combo"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cheque_radio)
                .addGap(18, 18, 18)
                .addComponent(cash_radio)
                .addGap(69, 69, 69)
                .addComponent(jLabel13)
                .addGap(5, 5, 5)
                .addComponent(payment_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(generate_button)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cash_radio)
                    .addComponent(cheque_radio)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(generate_button)
                    .addComponent(payment_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        xtrafees_check.setName("xtrafees_check"); // NOI18N
        xtrafees_check.setOpaque(false);
        xtrafees_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xtrafees_checkActionPerformed(evt);
            }
        });

        latefees_check.setName("latefees_check"); // NOI18N
        latefees_check.setOpaque(false);
        latefees_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                latefees_checkActionPerformed(evt);
            }
        });

        clear_buttton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        clear_buttton.setText("CLEAR");
        clear_buttton.setName("clear_buttton"); // NOI18N
        clear_buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_butttonActionPerformed(evt);
            }
        });

        jButton5.setText("Discount Rates");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tution_text, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(conveyence_text, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(xtrafees_text, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(xtrafees_check))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(latefees_text, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(latefees_check)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear_buttton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tution_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conveyence_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(xtrafees_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addComponent(xtrafees_check, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(latefees_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(latefees_check)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(clear_buttton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 760, 510));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/feeback.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 790, 533));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cheque_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheque_radioActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cheque_radioActionPerformed

private void cash_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cash_radioActionPerformed

// TODO add your handling code here:
}//GEN-LAST:event_cash_radioActionPerformed

private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
 try{ 
        
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
           
           Statement stmt1 = (Statement) con1.createStatement();
            
    String strSQL1 ="UPDATE fees SET fees_upto = DATE_ADD('"+(feesdate)+"', INTERVAL '"+(payment_combo.getSelectedItem().toString())+"' MONTH) WHERE enroll_no='"+(enroll)+"'";
      
    int rowsEffected1 = stmt1.executeUpdate(strSQL1);
            System.out.println(rowsEffected1 + " rows effected");
            con1.close();
            JOptionPane.showMessageDialog(this,(new javax.swing.ImageIcon(getClass().getResource("/paid.png"))));
 }
 catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            
 }
 
}//GEN-LAST:event_submit_buttonActionPerformed

private void verify_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_ButtonActionPerformed
int entered_enrollno=Integer.parseInt(scholar_textfield.getText());

                
        String query = "SELECT enroll_no,fees_upto FROM fees WHERE enroll_no='"+(entered_enrollno)+"'";
        enroll = null;
        //For class
        try{ 
        
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
           
           Statement stmt = (Statement) con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            
            while (rs.next()) {
                enroll = rs.getString("enroll_no");
               feesdate = rs.getString("fees_upto");
            }
            
            int real_enrollno=Integer.parseInt(enroll);
            if(real_enrollno==entered_enrollno)
            {
                String queryFINAL = "SELECT fname,lname,class,sec,photo,conveyence FROM admission WHERE enroll_no='"+(enroll)+"'";
        
     
        try{ 
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con1 = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
           
            Statement stmt1 = (Statement) con1.createStatement();
            ResultSet rs1 = stmt1.executeQuery(queryFINAL);
             
            while (rs1.next()) {
              
                String FName = rs1.getString("fname");
                String LName = rs1.getString("lname");
                 Classs = rs1.getString("class");
                String Sec = rs1.getString("sec");
                String Photo_URL = rs1.getString("photo");
                conveyence=rs1.getString("conveyence");
                name_text.setText(FName+""+LName);
                class_text.setText(Classs);
                section_text.setText(Sec);
                
                if(Photo_URL.equals(""))
                {
                    img_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nophoto.png")));
                }
                else
                {
                    
                    img_label.setIcon(new javax.swing.ImageIcon(Photo_URL));
                }
                
            }
            
           
               
            }
        
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"Enter the correct enrollment number");
        }
        generate_button.setEnabled(true);
            }
            
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Invalid Number");
            scholar_textfield.setText("");
           
        }
        
        
        
            
}//GEN-LAST:event_verify_ButtonActionPerformed

    private void generate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_buttonActionPerformed
int months=Integer.parseInt(payment_combo.getSelectedItem().toString());
int fees = 0;
        int cl=Integer.parseInt(Classs);
        if(cl==1)
        {
            fees=600;
        }
        else if(cl==2)
        {
            fees=650;
        }
        else if(cl==3)
        {
                        fees=700;

        }
        else if(cl==4)
        {
                        fees=750;

        }
        else if(cl==5)
        {
                        fees=800;

        }
        else if(cl==6)
        {
                        fees=850;

        }    
        else if(cl==7)
        {
                        fees=900;

        }
        else if(cl==8)
        {
                       fees=900;

        }
        else if(cl==9)
        {
                        fees=900;

        }
        else if(cl==10)
        {
                        fees=1000;

        }
        else if(cl==11)
        {
                        fees=1100;

        }
        else if(cl==12)
        {
                        fees=1400;
        }
        
        if(months==1)
        {
                int total=fees*months;
        tution_text.setText(""+total);
        if(conveyence.equals("Yes"))
        {
            conveyence_text.setText(""+(650*months));
        }
        else
        {
            conveyence_text.setText(""+0);
        }
        
        submit_button.setEnabled(true);        

        }
        else if(months==3)
        {
                        int total=fees*months;
        tution_text.setText(""+(total-total*0.005));
        if(conveyence.equals("Yes"))
        {
            conveyence_text.setText(""+(650*months));
        }
        else
        {
            conveyence_text.setText(""+0);
        }
        
        submit_button.setEnabled(true);

        }
        else if(months==6)
        {
                       int total=fees*months;
        tution_text.setText(""+(total-total*0.007));
        if(conveyence.equals("Yes"))
        {
            conveyence_text.setText(""+(650*months));
        }
        else
        {
            conveyence_text.setText(""+0);
        }
        
        submit_button.setEnabled(true); 

        }
        else if(months==12)
        {
                        int total=fees*months;
        tution_text.setText(""+(total-total*0.015));
        if(conveyence.equals("Yes"))
        {
            conveyence_text.setText(""+(650*months));
        }
        else
        {
            conveyence_text.setText(""+0);
        }
        
        submit_button.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_generate_buttonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    
    }//GEN-LAST:event_formWindowOpened

    private void formWindowDeiconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeiconified
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeiconified

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void xtrafees_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xtrafees_checkActionPerformed
if(xtrafees_check.isSelected())
{
    xtrafees_text.setEditable(true);
    
}
else
{
    xtrafees_text.setEditable(false);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_xtrafees_checkActionPerformed

    private void latefees_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_latefees_checkActionPerformed
if(latefees_check.isSelected())
{
    latefees_text.setEditable(true);
    
}
else
{
    latefees_text.setEditable(false);
}        // TODO add your handling code here:
    }//GEN-LAST:event_latefees_checkActionPerformed

    private void clear_butttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_butttonActionPerformed
scholar_textfield.setText("");
name_text.setText("");
class_text.setText("");
section_text.setText("");
tution_text.setText("");
payment_combo.setSelectedIndex(0);
conveyence_text.setText("");
latefees_text.setText("");
xtrafees_text.setText("");
xtrafees_check.setSelected(false);
latefees_check.setSelected(false);
generate_button.setEnabled(false);
submit_button.setEnabled(false);
xtrafees_text.setEditable(false);
latefees_text.setEditable(false);// TODO add your handling code here:
    }//GEN-LAST:event_clear_butttonActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JOptionPane.showMessageDialog(this,"1 month - no discount"+"\n"+"3 month - 5%"+"\n"+"6 month - 7%"+"\n"+"12 month - 15%"+"\n"+"excluding conveyence fess");// TODO add your handling code here:

}//GEN-LAST:event_jButton5ActionPerformed

private void editdate_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editdate_checkActionPerformed
if(date_button.isEditable())
{
    date_button.setEditable(false);
}
else
{
    date_button.setEditable(true);
}
        // TODO add your handling code here:
}//GEN-LAST:event_editdate_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecieveFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecieveFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecieveFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecieveFees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RecieveFees().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cash_radio;
    private javax.swing.JRadioButton cheque_radio;
    private javax.swing.JTextField class_text;
    private javax.swing.JButton clear_buttton;
    private javax.swing.JTextField conveyence_text;
    private javax.swing.JTextField date_button;
    private javax.swing.JCheckBox editdate_check;
    private javax.swing.JButton generate_button;
    private javax.swing.JLabel img_label;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JCheckBox latefees_check;
    private javax.swing.JTextField latefees_text;
    private javax.swing.JTextField name_text;
    private javax.swing.JComboBox payment_combo;
    private javax.swing.JTextField scholar_textfield;
    private javax.swing.JTextField section_text;
    private javax.swing.JButton submit_button;
    private javax.swing.JTextField tution_text;
    private javax.swing.JButton verify_Button;
    private javax.swing.JCheckBox xtrafees_check;
    private javax.swing.JTextField xtrafees_text;
    // End of variables declaration//GEN-END:variables
}
