
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * softpass.java
 *
 * Created on Nov 20, 2012, 11:47:06 AM
 */
/**
 *
 * @author Tilak
 */
public class Software_pass extends javax.swing.JFrame {
    String softwarepassword;
    String mysqlpass;
public Software_pass( String mysqlpassword)
    {
        initComponents();
        mysqlpass=mysqlpassword;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
        
    }
    
    public Software_pass() {
        initComponents();
        
        
    
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        softpass_field = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        ok_BUTTON = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Enter The Password");

        ok_BUTTON.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ok_BUTTON.setText("OK");
        ok_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_BUTTONActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Enter software Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(softpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ok_BUTTON, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(softpass_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok_BUTTON))
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ok_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_BUTTONActionPerformed
String query="SELECT password FROM password";
try{
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/svm","root",mysqlpass);
    Statement stmt=(Statement) con.createStatement();
    ResultSet rs=stmt.executeQuery(query);
    
    while(rs.next())
    {
        softwarepassword=rs.getString("password");
        
    }
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
}
String enteredpassword;
enteredpassword=softpass_field.getText();
if(enteredpassword.equals(softwarepassword))
{
    
    this.setVisible(false);
        new Home(mysqlpass).setVisible(true);
}
else
{
    JOptionPane.showMessageDialog(this,"Enter the correct password");
    String gethint="SELECT hint FROM password";
    try{
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    Connection con=(Connection)
            DriverManager.getConnection("jdbc:mysql://localhost:3306/svm","root",mysqlpass);
    Statement stmt=(Statement) con.createStatement();
    ResultSet rs=stmt.executeQuery(gethint);
    while(rs.next())
    {
       String hint=rs.getString("hint");
       jLabel4.setText("Hint :- "+hint);
       jLabel4.setVisible(true);
        softpass_field.setText("");
    }
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(this,e.getMessage());
}
    
}
}//GEN-LAST:event_ok_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Software_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Software_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Software_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Software_pass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Software_pass().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ok_BUTTON;
    private javax.swing.JPasswordField softpass_field;
    // End of variables declaration//GEN-END:variables
}
