
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShAdmission.java
 *
 * Created on Aug 19, 2012, 10:12:23 AM
 */
/**
 *
 * @author Tilak PC
 */
public class Student_search extends javax.swing.JFrame {

String query1,query2,query3,query4,query5,query6;
String finalquery,mysqlpass;
    /** Creates new form ShAdmission */
public Student_search( String mysqlpassword)
    {
        initComponents();
        mysqlpass=mysqlpassword;
        DefaultComboBoxModel model1 = (DefaultComboBoxModel) class_combo.getModel();
                
        String query = "SELECT DISTINCT class FROM admission ORDER BY class";
        String classs;
        model1.removeAllElements();
        //For class
        try{ 
        
            
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
           
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            
            while (rs.next()) {
                classs = rs.getString("class");
                model1.addElement(classs);
                
                
                
                
            }
            
            
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;
        this.setLocation(x, y);
        
       
        
        section_combo.setEnabled(false);
        hostel_combo.setEnabled(false);
        conveyence_combo.setEnabled(false);
        category_combo.setEnabled(false);
        
        
        
    }
    public Student_search() {
        initComponents();
        
        
        
        
        

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        class_combo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        section_combo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        hostel_combo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        conveyence_combo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        category_combo = new javax.swing.JComboBox();
        submitbutton = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        enterenroll_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        section_check = new javax.swing.JCheckBox();
        hostel_check = new javax.swing.JCheckBox();
        conveyence__check = new javax.swing.JCheckBox();
        category_check = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Selected Criterias", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        class_combo.setModel(new DefaultComboBoxModel());
        class_combo.setToolTipText("");
        class_combo.setName("Class"); // NOI18N
        class_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                class_comboActionPerformed(evt);
            }
        });
        class_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                class_comboFocusLost(evt);
            }
        });
        jPanel2.add(class_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 47, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("CLASS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 28));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEC");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 60, 28));

        section_combo.setModel(new DefaultComboBoxModel());
        section_combo.setToolTipText("");
        section_combo.setName("Class"); // NOI18N
        section_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                section_comboActionPerformed(evt);
            }
        });
        section_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                section_comboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                section_comboFocusLost(evt);
            }
        });
        jPanel2.add(section_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("HOSTEL");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 28));

        hostel_combo.setModel(new DefaultComboBoxModel());
        hostel_combo.setToolTipText("");
        hostel_combo.setName("Class"); // NOI18N
        hostel_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostel_comboActionPerformed(evt);
            }
        });
        hostel_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hostel_comboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                hostel_comboFocusLost(evt);
            }
        });
        jPanel2.add(hostel_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 58, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("CONVEYENCE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 28));

        conveyence_combo.setModel(new DefaultComboBoxModel());
        conveyence_combo.setToolTipText("");
        conveyence_combo.setName("Class"); // NOI18N
        conveyence_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conveyence_comboActionPerformed(evt);
            }
        });
        conveyence_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                conveyence_comboFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                conveyence_comboFocusLost(evt);
            }
        });
        jPanel2.add(conveyence_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 103, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setText("CATEGORY");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 28));

        category_combo.setModel(new DefaultComboBoxModel());
        category_combo.setToolTipText("");
        category_combo.setName("Class"); // NOI18N
        category_combo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                category_comboFocusGained(evt);
            }
        });
        jPanel2.add(category_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 81, -1));

        submitbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(submitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, -1));

        clear_button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear_button.setText("CLEAR");
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(clear_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 123, 810, 110));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Enroll No.", "First Name", "Last Name", "Class", "Section", "Sex", "DOB", "Address", "Imagelocation"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setOpaque(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(table);
        table.getColumnModel().getColumn(0).setResizable(false);
        table.getColumnModel().getColumn(0).setPreferredWidth(50);
        table.getColumnModel().getColumn(1).setResizable(false);
        table.getColumnModel().getColumn(1).setPreferredWidth(100);
        table.getColumnModel().getColumn(2).setResizable(false);
        table.getColumnModel().getColumn(2).setPreferredWidth(100);
        table.getColumnModel().getColumn(3).setResizable(false);
        table.getColumnModel().getColumn(3).setPreferredWidth(50);
        table.getColumnModel().getColumn(4).setResizable(false);
        table.getColumnModel().getColumn(4).setPreferredWidth(50);
        table.getColumnModel().getColumn(5).setResizable(false);
        table.getColumnModel().getColumn(5).setPreferredWidth(50);
        table.getColumnModel().getColumn(6).setResizable(false);
        table.getColumnModel().getColumn(6).setPreferredWidth(80);
        table.getColumnModel().getColumn(8).setMinWidth(0);
        table.getColumnModel().getColumn(8).setPreferredWidth(0);
        table.getColumnModel().getColumn(8).setMaxWidth(0);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 265, 810, 244));

        enterenroll_button.setText("Enter Enrollment number");
        enterenroll_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterenroll_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(enterenroll_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 190, 38));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("FOR COMPLETE INFORMATION ENTER THE ENROLLMENT NUMBER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, 38));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bluenotify.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, 35));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setText("Search Using");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 30));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        section_check.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        section_check.setText("Sec");
        section_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                section_checkActionPerformed(evt);
            }
        });

        hostel_check.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        hostel_check.setText("Hostel");
        hostel_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostel_checkActionPerformed(evt);
            }
        });

        conveyence__check.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        conveyence__check.setText("Conveyence");
        conveyence__check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conveyence__checkActionPerformed(evt);
            }
        });

        category_check.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        category_check.setText("Category");
        category_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(section_check)
                .addGap(34, 34, 34)
                .addComponent(hostel_check)
                .addGap(34, 34, 34)
                .addComponent(conveyence__check)
                .addGap(30, 30, 30)
                .addComponent(category_check)
                .addContainerGap(328, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(section_check)
                    .addComponent(hostel_check)
                    .addComponent(conveyence__check)
                    .addComponent(category_check))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 710, 50));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Class requirement is compulsory");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 210, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed

    
   
        
       

finalquery="SELECT * FROM admission WHERE class='"+(class_combo.getSelectedItem().toString())+"'";
    
    if(section_check.isSelected())
    {
        
        query2="sec='"+(section_combo.getSelectedItem().toString())+"'";
        finalquery=finalquery.concat("AND "+query2);
               
    }
    if(hostel_check.isSelected())
    {
        
        query3="hostel='"+(hostel_combo.getSelectedItem().toString())+"'";
        finalquery=finalquery.concat("AND "+query3);
               
    }
    if(conveyence__check.isSelected())
    {
        
        query4="conveyence='"+(conveyence_combo.getSelectedItem().toString())+"'";
        finalquery=finalquery.concat("AND "+query4);
               
    }
    if(category_check.isSelected())
    {
        
        query5="category='"+(category_combo.getSelectedItem().toString())+"'";
        finalquery=finalquery.concat("AND "+query5);
               
    }
    
    DefaultTableModel model = (DefaultTableModel) table.getModel();
        // Clear the existing table
        int rows = model.getRowCount();
        if (rows > 0) {
            for (int i = 0; i < rows; i++) {
                model.removeRow(0);
            }
        }

        String classs;
        //For class
        try{ 
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
           
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(finalquery);
             
            while (rs.next()) {
               String eno = rs.getString("enroll_no");
                String FName = rs.getString("fname");
                String LName = rs.getString("lname");
                String Classs = rs.getString("class");
                String Sec = rs.getString("sec");
                String Sex = rs.getString("sex");
                String dob = rs.getString("dob");
                String Add = rs.getString("address");
                String Pho = rs.getString("photo");
                
                
                
                model.addRow(new Object[] {eno, FName, LName, Classs , Sec, Sex, dob, Add, Pho});
            }
        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    
    
    
// TODO add your handling code here:
}//GEN-LAST:event_submitbuttonActionPerformed

private void class_comboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_class_comboFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_class_comboFocusLost

private void section_comboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_section_comboFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_section_comboFocusLost

private void hostel_comboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostel_comboFocusLost

// TODO add your handling code here:
}//GEN-LAST:event_hostel_comboFocusLost

private void conveyence_comboFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conveyence_comboFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_conveyence_comboFocusLost

private void section_comboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_section_comboFocusGained

    String querysection = "SELECT DISTINCT sec FROM admission WHERE class='"+(class_combo.getSelectedItem().toString())+"'ORDER BY sec";
try {
            DefaultComboBoxModel model2 = (DefaultComboBoxModel) section_combo.getModel();
    
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(querysection);
            String sec;
            model2.removeAllElements();
            
            while (rs.next()) {
                sec = rs.getString("sec");
                model2.addElement(sec);
                
                
            }
            
}
catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_section_comboFocusGained

private void class_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_class_comboActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_class_comboActionPerformed

private void section_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_section_comboActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_section_comboActionPerformed

private void hostel_comboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostel_comboFocusGained
DefaultComboBoxModel model3 = (DefaultComboBoxModel) hostel_combo.getModel();
    //ForHostel
        String queryhostel = "SELECT DISTINCT hostel FROM admission WHERE class='"+(class_combo.getSelectedItem().toString())+"' ORDER BY hostel";
try {
            model3.removeAllElements();
    
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(queryhostel);
            String hostel;
            
            while (rs.next()) {
                hostel = rs.getString("hostel");
                model3.addElement(hostel);
                
                
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }// TODO add your handling code here:
}//GEN-LAST:event_hostel_comboFocusGained

private void conveyence_comboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_conveyence_comboFocusGained
DefaultComboBoxModel model4 = (DefaultComboBoxModel) conveyence_combo.getModel();
    String queryconveyence = "SELECT DISTINCT conveyence FROM admission WHERE class='"+(class_combo.getSelectedItem().toString())+"'ORDER BY conveyence";

try {
            model4.removeAllElements();
    
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(queryconveyence);
            String conveyence;
            
            while (rs.next()) {
                conveyence = rs.getString("conveyence");
                model4.addElement(conveyence);
                
                
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }// TODO add your handling code here:
}//GEN-LAST:event_conveyence_comboFocusGained

private void hostel_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostel_comboActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_hostel_comboActionPerformed

private void conveyence_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conveyence_comboActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_conveyence_comboActionPerformed

private void category_comboFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_category_comboFocusGained
//for category
DefaultComboBoxModel model6 = (DefaultComboBoxModel) category_combo.getModel();
String querycategory = "SELECT DISTINCT category FROM admission WHERE class='"+(class_combo.getSelectedItem().toString())+"' ORDER BY category";

try {
            
    model6.removeAllElements();
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SVM","root",mysqlpass);
            // Create SQL statement and execute query.
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(querycategory);
            String category;
            
            while (rs.next()) {
                category = rs.getString("category");
                model6.addElement(category);
                
                
            }
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }// TODO add your handling code here:
}//GEN-LAST:event_category_comboFocusGained

private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
table.removeAll();
section_combo.removeAllItems();
hostel_combo.removeAllItems();
conveyence_combo.removeAllItems();
category_combo.removeAllItems();
section_check.setSelected(false);
hostel_check.setSelected(false);
conveyence__check.setSelected(false);
category_check.setSelected(false);
}//GEN-LAST:event_clear_buttonActionPerformed

private void enterenroll_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterenroll_buttonActionPerformed
new StudentInformation(mysqlpass).setVisible(true);
new StudentInformation(mysqlpass).setAlwaysOnTop(true);
// TODO add your handling code here:
}//GEN-LAST:event_enterenroll_buttonActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
}//GEN-LAST:event_formWindowOpened

private void section_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_section_checkActionPerformed
if(section_check.isSelected())
{
    section_combo.setEnabled(true);
}
else
{
    section_combo.setEnabled(false);
}// TODO add your handling code here:
}//GEN-LAST:event_section_checkActionPerformed

private void hostel_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostel_checkActionPerformed
if(hostel_check.isSelected())
{
    hostel_combo.setEnabled(true);
}
else
{
    hostel_combo.setEnabled(false);
}// TODO add your handling code here:
}//GEN-LAST:event_hostel_checkActionPerformed

private void conveyence__checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conveyence__checkActionPerformed
if(conveyence__check.isSelected())
{
    conveyence_combo.setEnabled(true);
}
else
{
    conveyence_combo.setEnabled(false);
}// TODO add your handling code here:
}//GEN-LAST:event_conveyence__checkActionPerformed

private void category_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_checkActionPerformed
if(category_check.isSelected())
{
    category_combo.setEnabled(true);
}
else
{
    category_combo.setEnabled(false);
}// TODO add your handling code here:
}//GEN-LAST:event_category_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Student_search().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox category_check;
    private javax.swing.JComboBox category_combo;
    private javax.swing.JComboBox class_combo;
    private javax.swing.JButton clear_button;
    private javax.swing.JCheckBox conveyence__check;
    private javax.swing.JComboBox conveyence_combo;
    private javax.swing.JButton enterenroll_button;
    private javax.swing.JCheckBox hostel_check;
    private javax.swing.JComboBox hostel_combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox section_check;
    private javax.swing.JComboBox section_combo;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
