import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CMBRunUI.java
 *
 * Created on Aug 2, 2009, 4:31:12 PM
 */

/**
 *
 * @author gagan
 */
public class CMBRunUI extends javax.swing.JFrame {

    /** Creates new form CMBRunUI */
    public CMBRunUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEname = new javax.swing.JTextField();
        btnCAdd = new javax.swing.JButton();
        btnCRemove = new javax.swing.JButton();
        btnCClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add/Remove/Clear operation using JComboBox control.");

        jLabel1.setText("Enter employee name:");

        btnCAdd.setText("Add");
        btnCAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAddActionPerformed(evt);
            }
        });

        btnCRemove.setText("Remove");
        btnCRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCRemoveActionPerformed(evt);
            }
        });

        btnCClear.setText("Clear");
        btnCClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCClearActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new DefaultComboBoxModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEname, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnCAdd)
                            .addComponent(btnCRemove)
                            .addComponent(btnCClear)
                            .addComponent(btnClose))
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCAdd)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCRemove)
                .addGap(18, 18, 18)
                .addComponent(btnCClear)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAddActionPerformed
        // Creating a String object Ename
        String Ename = txtEname.getText();
        // Creating a ComboBoxModel object cModel to perform DefaultComboBoxModel method operations
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) jComboBox1.getModel();
        // Method to add elements into jComboBox1 control
        cModel.addElement(Ename);
        // Sets the data model for jComboBox1 control
        jComboBox1.setModel(cModel);
        // Sets the txtEname to null
        txtEname.setText("");
    }//GEN-LAST:event_btnCAddActionPerformed

    private void btnCRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCRemoveActionPerformed
        // Creating a String object Ename
        String Ename = (String) jComboBox1.getSelectedItem();
        int ind = jComboBox1.getSelectedIndex();
        // Creating a ComboBoxModel object cModel to perform DefaultComboBoxModel method operations
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) jComboBox1.getModel();
        // Remove the data at ind position
        cModel.removeElementAt(ind);
        // This displays the deleted item in a message box.
        // Add the line, at top of the source code: import javax.swing.JOptionPane;
        JOptionPane.showMessageDialog(this, "Deleted name " + Ename);
        jComboBox1.setModel(cModel);
    }//GEN-LAST:event_btnCRemoveActionPerformed

    private void btnCClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCClearActionPerformed
        // Creating a ComboBoxModel object cModel to perform DefaultComboBoxModel method operations
        DefaultComboBoxModel cModel = (DefaultComboBoxModel) jComboBox1.getModel();
        // Clears the jComboBox1 through DefaultComboBoxModel
        cModel.removeAllElements();
    }//GEN-LAST:event_btnCClearActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CMBRunUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCAdd;
    private javax.swing.JButton btnCClear;
    private javax.swing.JButton btnCRemove;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEname;
    // End of variables declaration//GEN-END:variables

}
